// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQ2nAspAknhgrsbVzhjLHOsW_HRDHr4Do',
    appId: '1:675698248240:web:a06611c691deaea164bbf5',
    messagingSenderId: '675698248240',
    projectId: 'ivox-89f14',
    authDomain: 'ivox-89f14.firebaseapp.com',
    storageBucket: 'ivox-89f14.firebasestorage.app',
    measurementId: 'G-JY14H8019V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVCkGsiEwptbi7lQzNz3mWJJ7j19mkeT0',
    appId: '1:675698248240:android:988415c60db0de4e64bbf5',
    messagingSenderId: '675698248240',
    projectId: 'ivox-89f14',
    storageBucket: 'ivox-89f14.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCmIVuSo7xWQxsxY8L2agNWbZM4o6lf5A',
    appId: '1:675698248240:ios:258a7bdf9e112ba664bbf5',
    messagingSenderId: '675698248240',
    projectId: 'ivox-89f14',
    storageBucket: 'ivox-89f14.firebasestorage.app',
    iosBundleId: 'com.example.ivox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCmIVuSo7xWQxsxY8L2agNWbZM4o6lf5A',
    appId: '1:675698248240:ios:258a7bdf9e112ba664bbf5',
    messagingSenderId: '675698248240',
    projectId: 'ivox-89f14',
    storageBucket: 'ivox-89f14.firebasestorage.app',
    iosBundleId: 'com.example.ivox',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQ2nAspAknhgrsbVzhjLHOsW_HRDHr4Do',
    appId: '1:675698248240:web:3d1a97a4bf42b10164bbf5',
    messagingSenderId: '675698248240',
    projectId: 'ivox-89f14',
    authDomain: 'ivox-89f14.firebaseapp.com',
    storageBucket: 'ivox-89f14.firebasestorage.app',
    measurementId: 'G-Z7FX0MQVHV',
  );
}
